mai_web/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web_app.urls')),
]

web_app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'main'

urlpatterns = [
    path('', views.home, name='web_app_home'),
    path('about/', views.about, name='web_app_about'),
    path('message/', views.message, name='web_app_message'),
    path('trade_model/', views.tradeModel, name='web_app_trade_model'),
    path('option_model/', views.optionModel, name='web_app_option_model'),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web_app/models.py
from web_app.algo_model import riskModel, ticker
from .algo_model import importData, graphData, priceModel
from datetime import date, timedelta, datetime
from .mongoDB import mongoDB
from .message import message
import pandas as pd
# Create your models here.

def get_prices_interval(prices):
    if int(prices) <= 25:
        return 2.5
    elif int(prices) <= 200:
        return 5
    else:
        return 10

class Model:

    __instance = None
    def __new__(cls):
        if cls.__instance is None:
            cls.__instance = object.__new__(cls)
        return cls.__instance
    
    def __init__(self) -> None:
        self.DB = mongoDB.MongoDB()
        self.DB.connect_to_db()
        self.ticker = None
        self.graph = None
        self.riskModel = None
        self.priceModel = None
        self.email = message.Email()
    
    def get_db(self):
        return self.DB

    # download the ticker from the mongoDB database
    def get_all_ticker_from_db(self):
        wikiData = importData.Data()
        wikiData.read_wiki()
        allTicker = wikiData.get_all_ticker()
        currTicker = self.DB.get_all_ticker_from_db()
        allTicker.sort()
        currTicker.sort()

        for i in range(len(currTicker)):
            for j in range(len(allTicker)):
                if currTicker[i] == allTicker[j]:
                    allTicker[:] = allTicker[:j] + allTicker[j+1:]
                    break

        if currTicker == []:
            currTicker = []
        else:
            currTicker = ['Database List'] + ['------------'] + currTicker
        result = currTicker + ['------------'] + ['S&P 500 List'] + ['------------'] + allTicker
        return result

    def get_option_prices(self, tickerName, expirationDate):
        # get the last business day as well as the date bfore the last biz date
        # will run the code of the strike price based on the last biz date
        t = ticker.Ticker(tickerName)
        format = "%Y-%m-%d"
        # get the day of last date
        lastBizDay = datetime.now() - timedelta(days = 1)
        shift = timedelta(max(1,(lastBizDay.weekday() + 6) % 7 - 3))
        lastBizDay = lastBizDay - shift
        # get a whole years of data
        pDateBeforeLastBizDate = lastBizDay - timedelta(days = 360)
        lastBizDay = lastBizDay.strftime(format)
        pDateBeforeLastBizDate = pDateBeforeLastBizDate.strftime(format)

        # print("lastBizDay:%s, pDateBeforeLastBizDate:%s" % (lastBizDay, pDateBeforeLastBizDate))
        if self.DB.find_ticker_from_db(tickerName):
            data = self.DB.find_data_from_db(tickerName)
            df = pd.DataFrame(list(data))
            t.add_data_from_database(df)
            t.set_data_range(pDateBeforeLastBizDate, lastBizDay)
        else:
            t.import_data_range(pDateBeforeLastBizDate, lastBizDay)
            self.DB.insert_to_db(t)
        # t.import_data_range(pDateBeforeLastBizDate, lastBizDay)
        volatility = t.get_vol_from_data()

        # print(volatility)
        dateDiff = (datetime.strptime(expirationDate, format) - datetime.strptime(lastBizDay, format)).days / 365
        lastClosePrice = t.get_last_close_data()
        self.priceModel = priceModel.OptionModel(t)

        priceInterval = get_prices_interval(lastClosePrice)
        # put strike list
        putList = [int(lastClosePrice)-n*priceInterval for n in range(1, 8)]
        callList = [int(lastClosePrice)+n*priceInterval for n in range(1, 8)]         

        # the option model from the price model class
        putOptionList, callOptionList = [], []

        for put in putList:
            
            self.priceModel.set_base(lastClosePrice, put, dateDiff, volatility)
            self.priceModel.black_scholes_put(lastClosePrice, put, dateDiff, volatility)
            putPrice = "{:.2f}".format(self.priceModel.get_price())
            putOptionList.append(putPrice)
            # print('strike @ %s, BS put @%s' % (put, putPrice))
        
        for call in callList:
            self.priceModel.set_base(lastClosePrice, call, dateDiff, volatility)
            self.priceModel.black_scholes_call(lastClosePrice, call, dateDiff, volatility)
            callPrice = "{:.2f}".format(self.priceModel.get_price())
            callOptionList.append(callPrice)
            # print('strike @ %s, BS put @%s' % (put, callPrice))

        return [[lastClosePrice], putList, callList, putOptionList, callOptionList]

    # This will print the baisc graph as pic into the web page.
    def run_base_graph(self, tickerName, startDate, endDate, chartType='line'):
        g = graphData.GraphData()
        t = ticker.Ticker(tickerName)
        if self.DB.find_ticker_from_db(tickerName):
            data = self.DB.find_data_from_db(tickerName)
            df = pd.DataFrame(list(data))
            t.add_data_from_database(df)
            t.set_data_range(startDate, endDate)
        else:
            t.import_data_range(startDate, endDate)
            self.DB.insert_to_db(t)
        g.set_data(t, t.get_start_date(), t.get_end_date(), chartType)
        self.graph = g
        g.graph_plot()

    # VaR calculation will need the VaR model from the algo folder
    def get_VaR_value(self, startDate, endDate, tickers, positions):
        if tickers == [] or positions == []:
            raise "No position or ticker"
        # remove duplicate tickers and aggregate the position if any dup
        tickerDict = {}
        for i in range(len(tickers)):
            if tickers[i] in tickerDict.keys():
                tickerDict[tickers[i]] += positions[i]
            else:
                tickerDict[tickers[i]] = positions[i]
        self.riskModel = riskModel.RiskModel()
        positions = []
        for tickerName, p in tickerDict.items():
            t = ticker.Ticker(tickerName)
            if self.DB.find_ticker_from_db(tickerName):
                data = self.DB.find_data_from_db(tickerName)
                df = pd.DataFrame(list(data))
                t.add_data_from_database(df)
                t.set_data_range(startDate, endDate)
            else:
                t.import_data_range(startDate, endDate)
                self.DB.insert_to_db(t)       
            self.riskModel.set_ticker(t)
            positions.append(p)

        self.riskModel.set_position(*positions)
        return self.riskModel.calc_VaR()

    # send email to me
    def send_email(self, name, subject, fromEmail, msg):
        self.email.send_email(name, subject, fromEmail, msg)


# if __name__ == '__main__':

#     m = Model()
#     # g = graphData.GraphData()
#     t = ticker.Ticker('AAPL')
#     t.import_data_range('2021-01-01', '2021-12-31')
#     m.get_VaR_value('2021-01-01', '2021-12-31',['AAPL', 'A'], [100,150])
    # data = m.get_db().find_data_from_db('AAPL')
    # df = pd.DataFrame(list(data))
    # t.add_data_from_database(df)
    # t.set_data_range('2021-01-01', '2021-12-31')
    # g.set_data(t, t.get_start_date(), t.get_end_date(), 'line')
    # g.graph_plot()

web_app/views.py
from re import sub
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from matplotlib.style import context
from .models import Model
from datetime import date, timedelta

MODEL = Model()

def home(request):
    return render(request, 'web_app/home.html')

def about(request):
    return render(request, 'web_app/about.html')

# this is for sending message to the author
def message(request):
    if request.method == 'POST':
        userName = 'Anonymous' if request.POST['name'] == ',' else request.POST['name']
        subject = 'Anonymous' if request.POST['subject'] == '' else request.POST['subject']
        fromEmail = 'Anonymous' if request.POST['fromEmail'] == '' else request.POST['fromEmail']
        body= 'NA' if request.POST['msg'] == '' else request.POST['msg']
        MODEL.send_email(userName, subject, fromEmail, body)

    return render(request, 'web_app/message.html')

# trademodel get the VaR calculation, graph the model as well as percentage of the model into the
def tradeModel(request):
    if request.method == 'GET':
        ticker = MODEL.get_all_ticker_from_db()
        context = {
            'ticker': ticker
        }
        return render(request, 'web_app/tradeModel.html', context)
    if request.method == 'POST':
        # this is get the general ticker POST request
        startDate = '2021-01-01' if request.POST['startDate'] == '' else request.POST['startDate']
        endDate = '2021-06-30' if request.POST['endDate'] == '' else request.POST['endDate']
        if 'ticker' in request.POST:
            ticker = request.POST['ticker']
            chartType= 'line' if request.POST['chartType'] == '' else request.POST['chartType']
            MODEL.run_base_graph(ticker, startDate, endDate, chartType)
        # this is for the VaR calculation
        if 'positions[]' in request.POST:
            tickers = request.POST.getlist('tickers[]')
            positions = request.POST.getlist('positions[]')
            varList = MODEL.get_VaR_value(startDate, endDate, tickers, positions)
            context = {
                'varList': varList
            }
            return JsonResponse(context)           

    return render(request, 'web_app/tradeModel.html')

def optionModel(request):
    if request.method == 'GET':
        ticker = MODEL.get_all_ticker_from_db()
        context = {
            'ticker': ticker
        }
        return render(request, 'web_app/optionModel.html', context)
    if request.method == 'POST':
        if 'getStrikePrice' in request.POST:
            ticker = request.POST['ticker']
            expirationDate = request.POST['expirationDate']
            expirationDate = date.today().strftime("%Y-%m-%d") if request.POST['expirationDate'] == '' else request.POST['expirationDate']
            putCallList = MODEL.get_option_prices(ticker, expirationDate)
            context = {
                'putCallList': putCallList
            }
            return JsonResponse(context)    
    return render(request, 'web_app/optionModel.html')

web_app/templates/web_app/about.html
{% extends 'web_app/base.html' %}
{% block content %}
<table class="table caption-top">
    <caption>Release Notes</caption>
    <thead>
      	<tr>
			<th scope="col">#</th>
			<th scope="col">Version</th>
			<th scope="col">Date</th>
			<th scope="col">Details</th>
      	</tr>
    </thead>
    <tbody>
		<tr>
			<th scope="row">1</th>
			<td>Beta v0.1</td>
			<td>2022.02.24</td>
			<td>
				<p style="margin:0;">Base release to the site; This release include the stock saves in a database.</p>
				<p style="margin:0;">User can select the date range with the STOCK ticker from the S&P 500 list from the Wikipedia.</p>
				<p style="margin:0;">Base graph is also included on the release, with the selection of date range and the chart type.</p>
			</td>
		</tr>
		<tr>
			<th scope="row">2</th>
			<td>Beta v0.2</td>
			<td>2022.03.04</td>
			<td>
				<p style="margin:0;">Update with the value at risk calculator on the Model page.</p>
				<p style="margin:0;">The VaR calculation is using the simple return with the closing data.</p>
				<p style="margin:0;">The Model will present the portfolio with 95% and 99% confidence levels.</p>
				<p style="margin:0;">Multiple positions with the same ticker will be grouped automatically by the Model.</p>
			</td>
		</tr>
		<tr>
			<th scope="row">3</th>
			<td>Beta v0.3</td>
			<td>2022.05.11</td>
			<td>
				<p style="margin:0;">Small bug fixes for the presentation on the VaR and the Stock graph.</p>
				<p style="margin:0;">Add the Option Model with the capability to run the European Black-Scholes Model.</p>
				<p style="margin:0;">Add the risk-free parser class to pull the 10 years T bond rate from Yahoo Finance.</p>
				<p style="margin:0;">Re-do the README page.</p>
			</td>
		</tr>
    </tbody>
  </table>
    
{% endblock content %}

web_app/templates/web_app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
	<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script> 

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    {% if title %}
        <title>Home Page - {{ title }} </title>
    {% else %}
        <title>Home Page</title>
    {% endif %}

    <style>
        #navigation {
            font-size: x-large; 
        }
        .fixed-body {
            margin-bottom: 200px;
        }
        .fixed-bottom {
            position: fixed;
            margin: auto;
            height: 100px;
            width: 100%;
            bottom: 0px;
            background-color: white;
        }
    </style>

</head>
<body>
    <div class="fixed-body">
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <ul id='navigation' class="nav nav-pills ">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'main:web_app_home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:web_app_about' %}">About</a>
                    </li>
                </ul>
            </nav>
        </div>

        <div class="container">
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            {% block content %}{% endblock %}
        </div>
    </div>
    <div class="container text-center fixed-bottom">
        <footer>
            <div class="row">
                <!-- Footer Location -->
                <div class="col-lg-4 mb-5 mb-lg-0">
                    <h4 class="text-uppercase mb-4">Email</h4>
                    <p class="lead mb-0">maihe88@gmail.com</p>
                </div>

                <!-- Footer Social Icons -->
                <div class="col-lg-4 mb-5 mb-lg-0">
                    <h4 class="text-uppercase mb-4">Contact Me</h4>
                    <a class="lead mb-0" href="{% url 'main:web_app_message' %}">Send me a message</a>
                </div>

                <!-- Footer About Text -->
                <div class="col-lg-4">
                    <h4 class="text-uppercase mb-4">About Me<a href="https://www.linkedin.com/in/mai-he-08a6557b/">(Linkedin)</a></h4>
                    <p class="lead mb-0">Check out my
                        <a href="https://github.com/mablic">Github</a>
                    </p>
                </div>
            </div>
        </footer>
    </div>

    
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/feather-icons/dist/feather.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"> </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
</body>
</html>

web_app/templates/web_app/home.html
{% extends 'web_app/base.html' %}
{% block content %}
    <div class="card text-center">
        <div class="card-body">
            <h5 class="card-title" >Algorithm Trading Model</h5>
            <ul class="list-group list-group-flush">
                <li class="list-group-item"></li>
                <li class="list-group-item">Selection of the S&P 500 Tickers</li>
                <li class="list-group-item">Picture the Ticker with Date Range or Chart Type</li>
                <li class="list-group-item">VaR Measurement</li>
                <li class="list-group-item">Opetion Model with Black-Scholes Engine</li>
                <li class="list-group-item"></li>
            </ul>
            <a href="{% url 'main:web_app_trade_model' %}" class="btn btn-primary">Stock Model</a>
            <a href="{% url 'main:web_app_option_model' %}" class="btn btn-primary">Option Model</a>
        </div>
    </div>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
{% endblock content %}

web_app/templates/web_app/message.html
{% extends 'web_app/base.html' %}
{% block content %}
<html>
    <head>
        <title>Contact</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
        <link href='https://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
    </head>

    <body>
        <div class="container" style="padding-top: 10px;margin-top: 15%;">

            <div class="messages"></div>

                <div class="controls">

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="form_name">Firstname *</label>
                                <input id="form_name" type="text" name="name" class="form-control" placeholder="Please enter your firstname *" required="required" data-error="Firstname is required.">
                                <div class="help-block with-errors"></div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="form_lastname">Lastname *</label>
                                <input id="form_lastname" type="text" name="surname" class="form-control" placeholder="Please enter your lastname *" required="required" data-error="Lastname is required.">
                                <div class="help-block with-errors"></div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="form_email">Email *</label>
                                <input id="form_email" type="email" name="email" class="form-control" placeholder="Please enter your email *" required="required" data-error="Valid email is required.">
                                <div class="help-block with-errors"></div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="form_need">Please specify your need *</label>
                                <select id="form_need" name="need" class="form-control" required="required" data-error="Please specify your need.">
                                    <option value=""></option>
                                    <option value="General questions">General questions</option>
                                    <option value="Request for account">Request for account</option>
                                    <option value="Request for code">Request for code</option>
                                    <option value="Other">Other</option>
                                </select>
                                <div class="help-block with-errors"></div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="form_message">Message *</label>
                                <textarea id="form_message" name="message" class="form-control" placeholder="Message for me *" rows="4" required="required" data-error="Please, leave us a message."></textarea>
                                <div class="help-block with-errors"></div>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <button type="submit" class="btn btn-success btn-send" data-bs-target="#exampleModal" data-bs-toggle="modal" onclick="send_email()">Send message</button>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <p class="text-muted">
                            <strong>*</strong> These fields are required
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Notification</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <p id="modal_body">Message Sent!</p>
                    </div>
                </div>
            </div>
          </div>
    </body>
    <script>
        function send_email(ret){
            var firstName = document.getElementById("form_name").value;
            var lastName = document.getElementById("form_lastname").value;
            var fromEmail = document.getElementById("form_email").value;
            var subject = document.getElementById("form_need").value;
            var msg = document.getElementById("form_message").value;
            var modelBody = document.getElementById("modal_body");
            // console.log('name='+ firstName + ',' + lastName + ';subject=' + subject + ';msg='+ msg)
            if(firstName == '' || lastName == '' || fromEmail == ''){
                modelBody.textContent = "Please fillout the required fields before send!"
                return
            } 
            modelBody.textContent = "Message Sent!"
            $.ajax({
                type: 'post',
                headers: { "X-CSRFToken": '{{csrf_token}}' },
                data: {'name': firstName + ',' + lastName, 'fromEmail': fromEmail, 'subject': subject, 'msg': msg},
            }).done(function(result) {
                reloading()
            });
        };
        function reloading(){
            location.reload();
        }
    </script>
</html>
{% endblock content %}

web_app/templates/web_app/optionModel.html
{% extends 'web_app/base.html' %}
{% block content %}

<div class="input-group mb-3">
    <div class="input-group-prepend">
        <label class="input-group-text" for="TickerListInput">Ticker</label>
    </div>
    <select class="custom-select" id="TickerListInput">
        <option selected>Choose...</option>
        {% for t in ticker %}
            <option>{{ t }}</option>
        {% endfor %}
    </select>
    &emsp;&emsp;
    <div class="input-group-prepend">
        <span class="input-group-text">Expiration Date</span>
    </div>
    <div class="col-auto">
        <input type="date" class="form-control" id="expirationDate">
    </div>
    &emsp;&emsp;
    <button data-toggle="collapse" onclick="search_option_ticker()" class="btn btn-primary">Get Strike Prices</button>
</div>

<div class="container">
    <p class="fs-10 fst-italic">* Strike Width.<a href="https://www.investopedia.com/terms/s/strikeprice.asp" target="_blank">More</a></p>
</div>

<div class="container">
    <p class="fs-10 fst-italic" id="tickerLastPrice">Last Prices of Ticker:</p>
</div>

<table class="table">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Position</th>
        <th scope="col">Strike</th>
        <th scope="col">Black-Scholes Price</th>
      </tr>
    </thead>
    <tbody>
        <tr id="optionTable" style="display:none;">
            <td>...</td>
            <td>...</td>
            <td>...</td>
            <td>...</td>
        </tr>
    </tbody>
</table>

<script>
    function search_option_ticker(){
        var ticker = $('#TickerListInput option:selected').val();
        var expirationDate = document.getElementById("expirationDate").value;
        $.ajax({
            type: 'post',
            headers: { "X-CSRFToken": '{{csrf_token}}' },
            data: {'ticker': ticker, 'expirationDate': expirationDate ,'getStrikePrice': true},
        }).done(function(result) {
            console.log(result['putCallList'])
            tickerLastPrice = result['putCallList'][0][0]
            $("#tickerLastPrice")[0].innerText = "Last Prices of Ticker: " + tickerLastPrice;
            var $elem = $("#optionTable")
            // call prices
            remove_option_table()
            for (var i=0; i<result['putCallList'][2].length;i++){
                $clone = $elem.clone( true )
                $clone[0].style = ""
                $clone[0].id = "optionTableNew"
                $clone.find("td")[0].innerText = i + 1
                $clone.find("td")[1].innerText = "Call"
                $clone.find("td")[2].innerText = result['putCallList'][2][i]
                $clone.find("td")[3].innerText = result['putCallList'][3][i]
                $clone.insertAfter("table tbody tr:last")
            }

            // put prices
            for (var i=0; i<result['putCallList'][1].length;i++){
                $clone = $elem.clone( true )
                $clone[0].style = ""
                $clone[0].id = "optionTableNew"
                $clone.find("td")[0].innerText = i + 1
                $clone.find("td")[1].innerText = "Put"
                $clone.find("td")[2].innerText = result['putCallList'][1][i]
                $clone.find("td")[3].innerText = result['putCallList'][3][i]
                $clone.insertAfter("table tbody tr:last")
            }
        });
    }

    function remove_option_table(){
        for (var i=0; i<14;i++){
            $("#optionTableNew").remove()
        }
    }
</script>

{% endblock content %}